FROM node:23-alpine3.19 As build
WORKDIR /app
# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci

# Копируем остальной код клиента
COPY . .

# Собираем production билд
RUN npm run build

# 2. Production-образ на базе nginx
FROM nginx:1.27-alpine

# Копируем билд в директорию nginx
COPY --from=build /app/build /usr/share/nginx/html

# Копируем свой nginx конфиг (чтобы работали SPA-маршруты)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Запускаем nginx
#EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]


