services:
  server:
    container_name: server
    build: ./server/
    ports:
      - 8080:8080
    restart: always
    environment:
      - WS_SERVER_PORT=8080
  
  # client:
  #     container_name: client
  #     build: ./client/
  #     ports:
  #       - 3000:3000
  #     restart: always
  #     environment:
  #       - WS_SERVER_PORT=8080
  #     depends:
  #       - server